import React from 'react';
import ReactMarkdown from "react-markdown";
import remarkUnwrapImages from "remark-unwrap-images";
import rehypeRaw from "rehype-raw";

import Link from "next/link";
import Head from 'next/head'

import { getAllPosts, getSinglePost } from "../../utils/lib";
import NavBar from "../../components/Masthead";
import FeaturedImage from '../../components/FeaturedImage';
import PostFooter from "../../components/PostFooter";

import RhmFigure from '../../components/RhmFigure';
import RhmImage from '../../components/RhmImage';

import styles from '../../styles/Post.module.scss'

const Post = ({ content, frontmatter }) => {

  const pageTitle = `${frontmatter.title} | Blog | Hypertext Jockey`;

  return (
    <div>
      <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <FeaturedImage image={frontmatter.featuredImage} classes={styles.postFeaturedImage} />
        <div className={styles.postContainer}>
          <h1 className={styles.postTitle}>{frontmatter.title}</h1>
          <ReactMarkdown className={styles.postContent}
            components={{
              img: ({node, ...props}) => <RhmImage {...props} />,
              a: ({node, ...props}) => <Link {...props} />,
              figure: ({node, ...props}) => <RhmFigure {...props} />
            }}
            remarkPlugins={[[remarkUnwrapImages]]}
            rehypePlugins={[rehypeRaw]}
          >{content}</ReactMarkdown>    

          <PostFooter frontmatter={frontmatter} />
        </div>
      </main>    
    </div>
  )
}

export const getStaticProps = async ({ params }) => {
  const post = await getSinglePost(params.slug, "content");
  return {
    props: { ...post },
  };
};

export const getStaticPaths = async () => {
  const paths = getAllPosts("content").map( ({slug}) => ({params: {slug} }));
  return {
    paths,
    fallback: false,
  };
};

export default Post;