import Head from 'next/head'

import { getAllPosts } from '../../utils/lib'
import NavBar from '../../components/Masthead';
import BlogGrid from '../../components/BlogGrid';

const Blog = ({ posts }) => {

  return (
    <div>
      <Head>
        <title>Blog | Hypertext Jockey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <BlogGrid posts={posts} />

    </div>
  )
}

export const getStaticProps = async () => {
  const posts = getAllPosts("content");
  return {
    props: { posts }
  };
};
  
export default Blog;