import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import pageStyles from '../styles/Page.module.scss'
import { getAllPosts, getHomeContent } from '../utils/lib'
import { FC } from 'react';

import NavBar from '../components/Masthead';
import PostTeaser from '../components/PostTeaser';

interface HomeProps {
  staticContent: string,
  post:{
    slug: string,
    frontmatter: {
      title: string,
      description: string
    }
  }
}

const Home:FC<HomeProps> = ({ staticContent, post }) => {
  return (
    <div>
      <Head>
        <title>Hypertext Jockey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={pageStyles.pageContainer}>
        <section className={styles.homeIntro}>
          <p>
            { staticContent }  
          </p>
        </section>
        <section className={styles.homePost}>
          <PostTeaser key={post.slug} isHomeTeaser postSlug={post.slug} postData={post.frontmatter} />
        </section>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const post = getAllPosts("content").shift();
  const staticContent = getHomeContent("static");
  return {
    props: { staticContent,post }
  };
};

export default Home
