import Head from 'next/head'
import NavBar from '../../../components/Masthead';
import BlogGrid from '../../../components/BlogGrid';
import BlogHeader from '../../../components/BlogHeader';

import styles from '../../../styles/Page.module.scss'

import { getAllTermPosts, getTerms } from '../../../utils/lib'

function Category({ posts, term }) {
  term = term.replace(/-/g,' ');
  const pageTitle = `Posts categorized "${term}" | Hypertext Jockey`;
  return (
    <div>
      <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <BlogHeader termType='Category' term={term} />
      <BlogGrid posts={posts} />

    </div>
  )
}

export const getStaticPaths = async () => {
  const terms = await getTerms("content", "category");
  const paths = terms.map((category: string) => ({
    params: {
      category,
    }
  }));
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const posts = await getAllTermPosts("content", params.category, 'category');
  return {
    props: { 
      posts,
      term: params.category
     }
  };
};


export default Category
