import { GetStaticPaths, GetStaticProps } from 'next'
import { ParsedUrlQuery } from 'querystring'
import Head from 'next/head'
import NavBar from '../../../components/Masthead';
import BlogGrid from '../../../components/BlogGrid';
import BlogHeader from '../../../components/BlogHeader';

import { getAllTermPosts, getTerms } from '../../../utils/lib'

interface IParams extends ParsedUrlQuery {
  tag: string
}

type Props = {
  posts: [{
    slug: string,
    frontmatter: {
      title: string;
      publishDate: string;
      description: string;
      featuredImage: {
          url: string;
          alt: string;
      }     
    }
  }],
  term: string
}

function Tag({ posts, term }: Props) {
  term = term.replace(/-/g,' ');
  const pageTitle = `Posts tagged "${term}" | Hypertext Jockey`;
  return (
    <div>
      <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <BlogHeader termType='Tag' term={term} />
      <BlogGrid posts={posts} />

    </div>
  )
}

export const getStaticPaths:GetStaticPaths = async () => {
  const terms = await getTerms("content", "tags");
  const paths = terms.map((tag:string) => ({
    params: {
      tag,
    }
  }));
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps:GetStaticProps = async ({ params }) => {
  const { tag } = params as IParams;
  const posts = await getAllTermPosts("content", tag, 'tags');
  return {
    props: { 
      posts,
      term: tag
     }
  };
};


export default Tag
