import Head from 'next/head'
import NavBar from '../../../components/Masthead';
import BlogGrid from '../../../components/BlogGrid';
import BlogHeader from '../../../components/BlogHeader';

import { getAllTermPosts, getTerms } from '../../../utils/lib'

function Tags({ posts, term }) {
  term = term.replace(/-/g,' ');
  const pageTitle = `Posts tagged ${term} | Hypertext Jockey`;
  return (
    <div>
      <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <BlogHeader termType='Tag' term={term} />
      <BlogGrid posts={posts} />

    </div>
  )

}

export const getStaticPaths = async () => {
  const terms = await getTerms("content", "tags");
  const paths = terms.map( (tag:string) => ({
      params: {
          tag,
      }
  }));
  return {
      paths,
      fallback: false,
  };
};

export const getStaticProps = async ({params}) => {
    const posts = await getAllTermPosts("content", params.tag, 'tags');
    return {
        props: { 
          posts, 
          term: params.tag 
        }
    };
};


export default Tags
